// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudxTm2xWa_n4HT2TaRnrXqVTmvQOHvl4',
    appId: '1:47258835183:web:e1d0ba5b159e7339a3631a',
    messagingSenderId: '47258835183',
    projectId: 'flutter-demo-26ffb',
    authDomain: 'flutter-demo-26ffb.firebaseapp.com',
    databaseURL: 'https://flutter-demo-26ffb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-26ffb.appspot.com',
    measurementId: 'G-4Y26ZR9GPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn3cWAyIKLeYFqjH-6AxeBwjmBDlmTqv4',
    appId: '1:47258835183:android:88e47105ac4293eca3631a',
    messagingSenderId: '47258835183',
    projectId: 'flutter-demo-26ffb',
    databaseURL: 'https://flutter-demo-26ffb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-26ffb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXnFa37vEOhIwnLhcGC3Xcb_yYNPanBI',
    appId: '1:47258835183:ios:400b18caf105c24ea3631a',
    messagingSenderId: '47258835183',
    projectId: 'flutter-demo-26ffb',
    databaseURL: 'https://flutter-demo-26ffb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-26ffb.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXnFa37vEOhIwnLhcGC3Xcb_yYNPanBI',
    appId: '1:47258835183:ios:0f64cb02c6db1e23a3631a',
    messagingSenderId: '47258835183',
    projectId: 'flutter-demo-26ffb',
    databaseURL: 'https://flutter-demo-26ffb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-26ffb.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
